services:
  api:
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-default}
      AWS_SDK_LOAD_CONFIG: "1"
    volumes:
      - type: bind
        source: ${USERPROFILE}/.aws
        target: /root/.aws
        read_only: true